version: '3'

networks:
  monreseau:
    external: false

services:
  web:
    build: .
    container_name: monsite_web
    volumes:
      - sitestatics:/app/static_assets/                                                                                                                                                                                     
      - sitemedias:/app/medias/  
    depends_on:
      - db
    networks:
      - monreseau

  db:
    image: "postgres:latest"
    container_name: monsite_db
    environment:
      POSTGRES_PASSWORD: mypassword
    networks:
      - monreseau
    volumes:
      - pgdb:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19-alpine
    container_name: monsite_nginx
    volumes:
      - sitestatics:/home/app/web/static_assets
      - sitemedias:/home/app/web/medias
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - monreseau
    ports:
      - '86:80'

volumes:
   pgdb:
   sitestatics:
   sitemedias: